MindUV4/MindUV3/Controllers/ArtspacesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MindUV3.Models;

namespace MindUV3.Controllers
{
    public class ArtspacesController : Controller
    {
        private MindUV1_dbEntities db = new MindUV1_dbEntities();

        // GET: Artspaces
        public ActionResult Index(int page = 0)
        {
            const int pageSize = 10;
            var count = db.Artspaces.Count();
            var data = db.Artspaces.OrderBy(a => a.Id).Skip(page * pageSize).Take(pageSize).ToList();
            this.ViewBag.MaxPage = (count / pageSize) - (count % pageSize == 0 ? 1 : 0);
            this.ViewBag.Page = page;
            return View(data);
            //return View(db.Artspaces.Take(5).ToList());
        }
        // GET: Artspaces/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Artspaces artspaces = db.Artspaces.Find(id);
            if (artspaces == null)
            {
                return HttpNotFound();
            }
            return View(artspaces);
        }

        // GET: Artspaces/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Artspaces/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Organisation,Street,Suburb_Town,Postcode,Website,Rating")] Artspaces artspaces)
        {
            if (ModelState.IsValid)
            {
                db.Artspaces.Add(artspaces);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(artspaces);
        }

        // GET: Artspaces/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Artspaces artspaces = db.Artspaces.Find(id);
            if (artspaces == null)
            {
                return HttpNotFound();
            }
            return View(artspaces);
        }

        // POST: Artspaces/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Organisation,Street,Suburb_Town,Postcode,Website,Rating")] Artspaces artspaces)
        {
            if (ModelState.IsValid)
            {
                db.Entry(artspaces).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(artspaces);
        }

        // GET: Artspaces/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Artspaces artspaces = db.Artspaces.Find(id);
            if (artspaces == null)
            {
                return HttpNotFound();
            }
            return View(artspaces);
        }

        // POST: Artspaces/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Artspaces artspaces = db.Artspaces.Find(id);
            db.Artspaces.Remove(artspaces);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MindUV4/MindUV3/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MindUV3.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Data()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

MindUV4/MindUV3/Controllers/SportsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MindUV3.Models;

namespace MindUV3.Controllers
{
    public class SportsController : Controller
    {
        private MindUV1_dbEntities db = new MindUV1_dbEntities();

        // GET: Sports
        public ActionResult Index(int page = 0)
        {
            const int pageSize = 10;
            var count = db.Sports.Count();
            var data = db.Sports.OrderBy(s => s.SportId).Skip(page * pageSize).Take(pageSize).ToList();
            this.ViewBag.MaxPage = (count / pageSize) - (count % pageSize == 0 ? 1 : 0);
            this.ViewBag.Page = page;
            return View(data);
            //return View(db.Artspaces.Take(5).ToList());
        }
        // GET: Sports/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Sports sports = db.Sports.Find(id);
            if (sports == null)
            {
                return HttpNotFound();
            }
            return View(sports);
        }

        // GET: Sports/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Sports/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "SportId,Organisation,Street,Suburb_Town,Postcode,State,Business_Category,Rating")] Sports sports)
        {
            if (ModelState.IsValid)
            {
                db.Sports.Add(sports);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(sports);
        }

        // GET: Sports/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Sports sports = db.Sports.Find(id);
            if (sports == null)
            {
                return HttpNotFound();
            }
            return View(sports);
        }

        // POST: Sports/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "SportId,Organisation,Street,Suburb_Town,Postcode,State,Business_Category,Rating")] Sports sports)
        {
            if (ModelState.IsValid)
            {
                db.Entry(sports).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(sports);
        }

        // GET: Sports/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Sports sports = db.Sports.Find(id);
            if (sports == null)
            {
                return HttpNotFound();
            }
            return View(sports);
        }

        // POST: Sports/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Sports sports = db.Sports.Find(id);
            db.Sports.Remove(sports);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MindUV4/MindUV3/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}

<!-- Page Content -->
<section class="about" id="about">
    <div class="container">
        <!-- Page Heading/Breadcrumbs -->
        <h1 class="mt-4 mb-3">
            About
            <small>Mind U</small>
        </h1>
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                @Html.ActionLink("Home", "Index", "Home")
            </li>
            <li class="breadcrumb-item active">About</li>
        </ol>
        <!-- Intro Content -->

        <div class="row">
            <div class="col-lg-6">
                <img class="img-responsive" src="@Url.Content("~/Images/about/about_banner.jpg")" alt="About us">
            </div>
            <div class="col-lg-6">
                <h2>MindU Project</h2>
                <p>MindU is a project aiming at helping the people who are concerned about international students struggling with stress, anxiety and loneliness in Victoria.</p>
                <p>We provide arts, sports and mental health relevant information for you to help the international students and their friends to overcome mental health issues.</p>
                <p>Whether you are new to melbourne or a person who does not know how to help your international student friends, looking for a way out of negative moods, welcome to visit MindU to have a goodtime and give feedback for our project.</p>
            </div>
        </div>
</section>
<!-- /.row -->
<hr>
<!-- Team Members -->
<div class="container">
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            Team Information
        </li>
    </ol>
    <div class="row">
        <div class="col-lg-3 col-sm-6 portfolio-item">
            <div class="card h-100">
                <div class="imagecontainer">
                    <img class="img" src="@Url.Content("~/Images/about/people1.jpg")" alt="team member1">
                </div>
                <div class="card-body">
                    <p class="card-text" style="text-align:center; font:bolder">     Jiang Wang</p>
                </div>

            </div>
        </div>
        <div class="col-lg-3 col-sm-6 portfolio-item">
            <div class="card h-100">
                <div class="imagecontainer">
                    <img class="img" src="@Url.Content("~/Images/about/people2.jpg")" alt="team member2">
                </div>
                <div class="card-body">
                    <p class="card-text" style="text-align:center; font:bolder;">    Yinig Ye</p>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-sm-6 portfolio-item">
            <div class="card h-100">
                <div class="imagecontainer">
                    <img class="img" src="@Url.Content("~/Images/about/people3.jpg")" alt="team member3"></a>
                </div>
                <div class="card-body">
                    <p class="card-text" style="text-align:center; font:bolder">     Yuanbo Liang</p>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-sm-6 portfolio-item">
            <div class="card h-100">
                <div class="imagecontainer">
                    <img class="img" src="@Url.Content("~/Images/about/people4.jpg")" alt="team member4">
                </div>
                <div class="card-body">
                    <p class="card-text" style="text-align:center; font:bolder">     Tanveer Siddiquee</p>
                </div>
            </div>
        </div>
        <!-- /.row -->
    </div>
</div>

MindUV4/MindUV3/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}

<!-- Page Content -->
<div class="container">
    <!-- Page Heading/Breadcrumbs -->
    <h1 class="mt-4 mb-3">
        Contact
        <small>Mind U</small>
    </h1>
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="index.html">Home</a>
        </li>
        <li class="breadcrumb-item active">Contact</li>
    </ol>
    <!-- Content Row -->
    <div class="row">
        <!-- Map Column -->
        <div class="col-lg-8 mb-4">
            <!-- Embedded Google Map -->
            <iframe src="https://maps.google.com/maps?q=-37.8770097,145.0442673&z=15&output=embed" width="100%;" height="400px;" frameborder="0" scrolling="no" marginheight="0" marginwidth="0"></iframe>
        </div>
        <!-- Contact Details Column -->
        <div class="col-lg-4 mb-4">
            <h3>Contact Details</h3>
            <p>
                900 Dandenong Rd,
                <br>Caulfield East VIC 3145
                <br>
            </p>
            <p>
                <abbr title="Phone">Phone</abbr>: +61 3 9902 6011
            </p>
            <p>
                <abbr title="Email">Email</abbr>:
                <a href="mailto:name@example.com">
                    ehelp@mindu.com
                </a>
            </p>
            <p>
                <abbr title="Hours">Hours</abbr>: Monday - Friday: 9:00 AM to 5:00 PM
            </p>
        </div>
    </div>
    <!-- /.row -->

MindUV4/MindUV3/Views/Home/Data.cshtml
@{
    ViewBag.Title = "Data";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 style="text-align:center">

    Community Mental Health Statistics
        
 </h2>

<div class="barcontainer">
    <div align=center>
        <img align="middle" src="~/Images/data/bar.jpg">
    </div>
    <p style="text-align:justify; font-size:larger">This bar graph is a comparison of some basic mental disorders in young university students in Australia diagnosed in the year 2015 – 2016.</p>
    <p style="text-align:justify; font-size:larger">This graph shows where Victoria stands against in mental health issues compared to the national data.</p>
    <p style="text-align:justify; font-size:larger">The greatest reported case on mental health issue is Depression followed by personality disorders, behavioral disorder, anxiety, adjustment disorder, eating and affective disorders. </p>
</div>
<div class="piecontainer">
    <br />
    <br />

    <div align=center>
        <img align="middle" src="~/Images/data/pie.jpg">
    </div>
    <p style="text-align:justify; font-size:larger">
        The pie chart shows the most common disorders diagnosed in Victoria, Australia.
    </p>
    <p style="text-align:justify; font-size:larger">
        The data shows depression is the most common form of mental illness.Among the mental health issues 73.04% is diagnosed with depression, which is very alarming.
    </p>
</div>

MindUV4/MindUV3/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home";
}

        <script>
            loopy()
            function loopy() {
                var flag = 0
                var sWord = ""
                while (flag == 0 && sWord != "MindU123") {
                    sWord = prompt("Please enter the password for the website.")
                }
                flag = 1;
                alert("Welcome to our website")
            }
    </script>
<!--Carousel-->
<div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
    </ol>
    <!-- Wrapper for slides -->
    <div class="carousel-inner">
        <div class="item active">
            <img src="@Url.Content("~/Images/banners/banner1.jpg")" alt="Mind U" style="width:100%;">
            <div class="carousel-caption">
                <h1>MindU</h1>
                <p style="font-size:x-large">You are not alone</p>
            </div>
        </div>
        <div class="item">
            <img src="@Url.Content("~/Images/banners/banner2.jpg")" alt="Mental Health" style="width:100%;">
            <div class="carousel-caption">
                <h1>Mental Health</h1>
                <p style="font-size:larger">We are here to help</p>
            </div>
        </div>
    </div>
    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right"></span>
        <span class="sr-only">Next</span>
    </a>
</div>
<!--/.Carousel-->
<!-- Page Content -->
<section class="services" id="services">
    <div class="container">
        <!-- Portfolio Section -->
        <h2 class="text-center text-uppercase text-secondary mb-0">Services</h2>
        <div class="row">
            <div class="col-lg-4 col-sm-6 portfolio-item">
                <div class="card h-100">
                    <a href='@Url.Action("Index", "Artspaces")'>
                        <img class="card-img-top" src="@Url.Content("~/Images/boxes/arts.jpg")" alt="">
                    </a>
                </div>
            </div>
            <div class="col-lg-4 col-sm-6 portfolio-item">
                <div class="card h-100">
                    <a href='@Url.Action("Index", "Sports")'><img class="card-img-top" src="@Url.Content("~/Images/boxes/sports.jpg")" alt=""></a>
                </div>
            </div>
            <div class="col-lg-4 col-sm-6 portfolio-item">
                <div class="card h-100">
                    <a href='@Url.Action("Data", "Home")'><img class="card-img-top" src="@Url.Content("~/Images/boxes/statistics.jpg")" alt=""></a>
                </div>
                <div class="card">
                </div>
            </div>
            <!-- /.row -->
        </div>
    </div>
</section>
<!-- /.container -->
<!-- About Section -->
<section class="bg-primary text-white mb-0" id="about">
    <div class="container">
        <h2 class="text-center text-uppercase text-white">About</h2>
        <hr class="star-light mb-5">
        <div class="row">
            <div class="col-lg-4 ml-auto">
                <p class="lead">MindU is a project aiming at helping people who are concerned with international students who are struggling with stress, anxiety and loneliness in VIC. </p>
            </div>
            <div class="col-lg-4 mr-auto">
                <p class="lead">We provide art spaces, sports and mental health relevant information for you to help your international student friend  get engaged in a more bright world!!! </p>
            </div>
            <div class="col-lg-4 mr-auto">
                <p class="lead">Whether you are new to melbourne or a person who does not know how to help your international friend get out of negative mood, welcome to visit MindU to have fun and give feedback for our project.</p>
            </div>
        </div>
    </div>
</section>